name: tpc_ops
description: TPC Operations - Ticket Scanning System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Backend (ready for future integration)
  supabase_flutter: ^2.5.6

  # Scanner
  mobile_scanner: ^5.1.1

  # Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  shared_preferences: ^2.2.3

  # UI Components
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2

  # Feedback
  vibration: ^3.0.0
  audioplayers: ^6.0.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  permission_handler: ^12.0.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
    - assets/icon/
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
